SEARCH_SUBTITLES_RESPONSE = {
    "sub": {
        "subs": [
            {
                "subtype": "SSA",
                "vote_score": 0,
                "videoname": "不知道",
                "release_site": "迪幻字幕组",
                "id": 710788,
                "lang": {
                    "langlist": {"langeng": True, "langchs": True, "langdou": True},
                    "desc": "英 简 双语",
                },
                "native_name": "安多.第二季.Andor.S02.2160p.DSNP.WEB-DL.适配HDR",
                "upload_time": "2025-11-03 05:10:33",
                "revision": 0,
            },
            {
                "subtype": "SSA",
                "vote_score": 0,
                "videoname": "不知道",
                "release_site": "迪幻字幕组",
                "id": 710396,
                "lang": {
                    "langlist": {"langeng": True, "langchs": True, "langdou": True},
                    "desc": "英 简 双语",
                },
                "native_name": "安多.第一季.Andor.S01.2160p.DSNP.WEB-DL.适配HDR",
                "upload_time": "2025-09-30 08:53:43",
                "revision": 0,
            },
            {
                "subtype": "SSA",
                "vote_score": 0,
                "videoname": "不知道",
                "release_site": "迪幻字幕组",
                "id": 710274,
                "lang": {
                    "langlist": {"langeng": True, "langchs": True, "langdou": True},
                    "desc": "英 简 双语",
                },
                "native_name": "迪幻字幕组 Star.Wars.Andor.S02E03.Harvest.1080p.DSNP.WEB-DL",
                "upload_time": "2025-07-13 17:39:38",
                "revision": 0,
            },
            {
                "subtype": "SSA",
                "vote_score": 0,
                "videoname": "不知道",
                "release_site": "迪幻字幕组",
                "id": 710273,
                "lang": {
                    "langlist": {"langeng": True, "langchs": True, "langdou": True},
                    "desc": "英 简 双语",
                },
                "native_name": "迪幻字幕组 Star.Wars.Andor.S02E02.Sagrona.Teema.1080p.DSNP.WEB-DL",
                "upload_time": "2025-07-13 17:39:02",
                "revision": 0,
            },
            {
                "subtype": "SSA",
                "vote_score": 0,
                "videoname": "不知道",
                "release_site": "迪幻字幕组",
                "id": 710272,
                "lang": {
                    "langlist": {"langeng": True, "langchs": True, "langdou": True},
                    "desc": "英 简 双语",
                },
                "native_name": "迪幻字幕组 Star.Wars.Andor.S02E01.One.Year.Later.1080p.DSNP.WEB-DL",
                "upload_time": "2025-07-13 17:39:00",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699871,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E12.Jedha.Kyber.Erso.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX【季终】",
                "upload_time": "2025-05-19 08:22:00",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699870,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E11.Who.Else.Knows.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-19 08:21:58",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699869,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E10.Make.It.Stop.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-19 08:21:37",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699781,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E06.What.a.Festive.Evening.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-08 01:20:32",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699780,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E05.I.Have.Friends.Everywhere.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-08 01:18:05",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699779,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E04.Ever.Been.to.Ghorman.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-08 01:18:01",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699741,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E03.Harvest.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-07 23:46:40",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699740,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E02.Sagrona.Teema.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-07 23:46:35",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699739,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "安多.Star.Wars.Andor.S02E01.One.Year.Later.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-05-07 23:35:51",
                "revision": 0,
            },
            {
                "subtype": "Subrip(srt)",
                "vote_score": 0,
                "videoname": "不知道",
                "id": 699086,
                "lang": {
                    "langlist": {
                        "langeng": True,
                        "langchs": True,
                        "langcht": True,
                        "langdou": True,
                    },
                    "desc": "英 简 繁 双语",
                },
                "native_name": "星球大战：骨干小队.Star.Wars.Skeleton.Crew.S01E08.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-FLUX",
                "upload_time": "2025-01-15 21:37:16",
                "revision": 0,
            },
        ],
        "action": "search",
        "keyword": "star wars",
        "result": "succeed",
    },
    "status": 0,
}
